version: '3'
services:
  winter:
    build:
      context: 'winter'
      dockerfile: 'Dockerfile-${PHP_VERSION}'
      args:
        - 'BACK_END=${BACK_END}'
        - 'USER_ID=${USER_ID}'
        - 'GROUP_ID=${GROUP_ID}'
        - 'PHP_VERSION=${PHP_VERSION}'
        - 'DISPLAY_PHPERROR=${DISPLAY_PHPERROR}'
        - 'XDEBUG=${XDEBUG}'
        - 'INSTALL_ADDITIONAL_EXTENSIONS=${INSTALL_ADDITIONAL_EXTENSIONS}'
        - 'DB_NAME=${DB_NAME}'
        - 'DB_USER=${DB_USER}'
        - 'DB_PASSWORD=${DB_PASSWORD}'
        - 'ADMIN_PASSWD=${ADMIN_PASSWD}'
    volumes:
      - '${APP_CODE_PATH_HOST}:${APP_CODE_PATH_WINTER}${APP_CODE_CONTAINER_FLAG}'
    ports:
      - '${WINTER_HOST_HTTP_PORT}:80'
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    environment:
      - 'MARIADB_DATABASE=${DB_NAME}'
      - 'MARIADB_USER=${DB_USER}'
      - 'MARIADB_PASSWORD=${DB_PASSWORD}'
      - 'MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
    volumes:
      - '${DATA_PATH_HOST}:/var/lib/mysql'
    ports:
      - '${MYSQL_PORT}:3306'
  phpmyadmin:
    image: ghcr.io/deck-app/phpmyadmin:5.2
    environment:
      - 'PMA_ARBITRARY=1'
      - 'MYSQL_USER=${DB_USER}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}'
    ports:
      - '${PMA_PORT}:80'
volumes: {}
